class Locators:
    FIRST_NAME_INPUT = "[data-cy='userForm-firstName']"
    LAST_NAME_INPUT = "[data-cy='userForm-lastName']"
    EMAIL_INPUT = "[data-cy='userForm-email']"
    PHONE_INPUT = "[data-cy='userForm-phoneNumber']"
    ORG_NAME_MENU = "[data-cy='userForm-organizationId-select']"
    ORG_NAME_INPUT = "[data-cy='userForm-organizationId-select'] .ant-select-selection-search-input"
    ORG_NAME_OPTION = ".ant-select-item-option-content:text-is('{}')"
    ORG_NAME_SAVED = "[data-cy='userForm-organizationId-select'] .ant-select-selection-item"
    NOTAM_OFFICE = "[data-cy='userForm-nof']"
    CANCEL_BUTTON = "[data-cy='createUser-button-cancel']"
    SAVE_BUTTON = "[data-cy='createUser-button-save']"
    SUCCESS_MESSAGE = "div.ant-notification-notice-description:text-is('{}')"
    CLOSE_BUTTON = "[data-cy='cancel-button']"
    ACTIVATE_BUTTON = "[data-cy='activate-button']"
    DEACTIVATE_BUTTON = "[data-cy='deactivate-button']"
    CONFIRM_ACTIVATE_BUTTON = "[data-cy='submit-button']"
    CONFIRM_DEACTIVATE_BUTTON = "[data-cy='submit-button']"
    EDIT_USER_BUTTON = "[data-cy='edit-button']"
    SAVE_UPDATED_USER_BUTTON = "[data-cy='updateUser-button-save']"
    CLOSE_MESSAGE_POPUP_BUTTON = ".ant-notification-notice-close"
    GENERIC_CHECKED_ROLE = ".ant-checkbox:has(input[checked]) + span"
